### ISSUE TITLE
How to split strings with spaces?

### ISSUE THREAD

**Issue by thomasd3** [cannorin/FSharp.CommandLine#1]
let t = "abc def 1.0"
let (a: string, b: string, c: float) = sscanf "%s %s %f" t

a, b, c

will return:

<img width="167" alt="image" src="https://user-images.githubusercontent.com/14313218/72226645-a69d1b00-3593-11ea-9676-e825b5a9b02c.png">

Is there a way to extract words separated by spaces?

**Comment by thomasd3** [comment]
sorry, wrote this in the wrong package page :D

**Comment by cannorin** [comment]
I consider this be a bug. I'll investigate and try to fix.

**Comment by cannorin** [comment]
Fixed in 3.2.3671.6874.
