### ISSUE TITLE
Creating GitHub releases

### ISSUE THREAD

**Issue by applejag** [cannorin/FSharp.CommandLine#10]
Hi! This is just a small suggestion

I use the watching of repos releases a lot to stay up to date with what new features are out in different repos. Do you have any plans on tagging your releases and making github releases out of them? (You know, those that are found here: https://github.com/cannorin/FSharp.CommandLine/releases)

Kind regards

**Comment by cannorin** [comment]
Honestly I didn't expect this library becomes to be used by many people (anyone besides me 😅). 

I think I must maintain this library much more from now on. Thank you for your suggestion!

**Comment by applejag** [comment]
You mustn't do anything. Don't feel obligated just because I'm putting some pressure on you :)
